services:
    mariadb:
        container_name: mariadb
        image: mariadb:10.11
        restart: always
        environment:
            - MARIADB_ROOT_PASSWORD=test
        ports:
            - '3306:3306'
        volumes:
            - mariadb:/var/lib/mysql

volumes:
    mariadb: {}
