spring:
    application:
        name: demo
    datasource:
        driverClassName: org.mariadb.jdbc.Driver
        url: jdbc:mariadb://localhost:3306/demo?createDatabaseIfNotExist=true&autoReconnect=true&rewriteBatchedStatements=true
        username: admin
        password: password
    jpa:
        hibernate:
            ddl-auto: validate
        generate-ddl: false
    data:
        rest:
            detection-strategy: annotated
